// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5fwL6nc5C5n0KD-hn9IQU804oQy-wDQs',
    appId: '1:240071763074:web:def1161de0ad04e382c09b',
    messagingSenderId: '240071763074',
    projectId: 'flutterfirst-29370',
    authDomain: 'flutterfirst-29370.firebaseapp.com',
    databaseURL: 'https://flutterfirst-29370-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirst-29370.appspot.com',
    measurementId: 'G-YF4SDGDQ9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALRFAp2mi1j4B-oAhTATSgIil9rqT1Sko',
    appId: '1:240071763074:android:0cd551077decdc4382c09b',
    messagingSenderId: '240071763074',
    projectId: 'flutterfirst-29370',
    databaseURL: 'https://flutterfirst-29370-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirst-29370.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUffOqXgLrfDqVuVGlH8tanKeVE7y-n8',
    appId: '1:240071763074:ios:1c206171acdd112b82c09b',
    messagingSenderId: '240071763074',
    projectId: 'flutterfirst-29370',
    databaseURL: 'https://flutterfirst-29370-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirst-29370.appspot.com',
    androidClientId: '240071763074-u6lem6sus5v8s82q74rn47156o2v2c99.apps.googleusercontent.com',
    iosClientId: '240071763074-dhbgnp8av7pjfl0a03vsrgm1n29vlfa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUffOqXgLrfDqVuVGlH8tanKeVE7y-n8',
    appId: '1:240071763074:ios:ec849ca4357e609782c09b',
    messagingSenderId: '240071763074',
    projectId: 'flutterfirst-29370',
    databaseURL: 'https://flutterfirst-29370-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirst-29370.appspot.com',
    androidClientId: '240071763074-u6lem6sus5v8s82q74rn47156o2v2c99.apps.googleusercontent.com',
    iosClientId: '240071763074-cp3nh8g5dhoohsa0rvr098sgq33fcmad.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth.RunnerTests',
  );
}
